### ISSUE TITLE
plot_denoising crashes when using n_jobs=2 with python 3

### ISSUE THREAD

**Issue by ckiefer0** [jdammers/jumeg#189] opened 2019-03-19 08:49 UTC
It works fine with n_jobs=1. This is the error:

sklearn.externals.joblib.externals.loky.process_executor._RemoteTraceback:
'''
Traceback (most recent call last):
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/sklearn/externals/joblib/externals/loky/process_executor.py", line 624, in _queue_management_worker
    result_item = result_reader.recv()
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/pickle.py", line 1600, in _loads
    encoding=encoding, errors=errors).load()
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/pickle.py", line 1382, in load_stack_global
    self.append(self.find_class(module, name))
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/pickle.py", line 1423, in find_class
    __import__(module, level=0)
ImportError: dlopen(/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so, 2): Symbol not found: __PyEval_GetBuiltinId
  Referenced from: /Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/lib-dynload/_pickle.cpython-37m-darwin.so
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "1_preprocessing.py", line 58, in <module>
    state_space_fname)
  File "/Users/kiefer/mne/jumeg3_true/pipelines/utils.py", line 93, in noise_reduction
    n_jobs=2, fnout=op.join(dirname, plot_name), show=False)
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/jumeg/jumeg_noise_reducer.py", line 152, in plot_denoising
    n_jobs=n_jobs, proj=proj)
  File "<string>", line 2, in psd_welch
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/mne/utils.py", line 952, in verbose
    return function(*args, **kwargs)
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/mne/time_frequency/psd.py", line 211, in psd_welch
    n_jobs=n_jobs, verbose=verbose)
  File "<string>", line 2, in psd_array_welch
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/mne/utils.py", line 952, in verbose
    return function(*args, **kwargs)
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/mne/time_frequency/psd.py", line 127, in psd_array_welch
    for d in x_splits)
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 930, in __call__
    self.retrieve()
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/kiefer/miniconda3/envs/py_3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
sklearn.externals.joblib.externals.loky.process_executor.BrokenProcessPool: A result has failed to un-serialize. Please ensure that the objects returned by the function are always picklable.

**Comment by pravsripad** [comment] 2019-03-19 10:39
I cannot reproduce this.

**Comment by pravsripad** [comment] 2019-04-17 09:28
@ckiefer0 can you confirm if this was a problem specific to your setup?

**Comment by pravsripad** [comment] 2019-11-08 15:55
Closing this.

**Closed by pravsripad** 2019-11-08 15:55 UTC
